SePantry-1/Controllers/AdminDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SePantry_1.Models;
using System.Data;
using System.Data.Entity;

namespace SePantry_1.Controllers
{
    public class AdminDashboardController : Controller
    {

        private UsersContext db = new UsersContext();

        // GET: AdminDashboard
        public ActionResult Index()
        {
            //Let the authorized admin view the Dashboard
            if (Roles.GetRolesForUser().Contains("Admin"))
            {
                return View();
            }
            else
            {
                //Redirect the non-authorized users to homepage
                return RedirectToAction("Login", "Account");
            }
        }

        // GET: /Active_Products/Create
        [Authorize(Roles = "admin")]
        public ActionResult CreateProducts()
        {
            return View();
        }

        //
        // POST: /Active_Products/Create

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProducts(Active_Product active_product)
        {
            if (ModelState.IsValid)
            {
                db.Active_Products.Add(active_product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(active_product);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Search_Inventory()
        {
            if (!string.IsNullOrEmpty(Request.Form["search-inventory"]))
            {
                
            }
            return View();
        }
    }
}

SePantry-1/Controllers/PDonorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SePantry_1.Models;

namespace SePantry_1.Controllers
{
    public class PDonorsController : Controller
    {
        private UsersContext db = new UsersContext();

        // GET: PDonors
        public ActionResult Index()
        {
            return View(db.Donors.ToList());
        }

        // GET: PDonors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // GET: PDonors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PDonors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,EmailAddress,DateRegistered")] Donor donor)
        {
            if (ModelState.IsValid)
            {
                donor.DateRegistered = DateTime.UtcNow;

                db.Donors.Add(donor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(donor);
        }

        // GET: PDonors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // POST: PDonors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,EmailAddress,DateRegistered")] Donor donor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(donor);
        }

        // GET: PDonors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // POST: PDonors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Donor donor = db.Donors.Find(id);
            db.Donors.Remove(donor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SePantry-1/Controllers/UserProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SePantry_1.Models;
using PagedList;
using PagedList.Mvc;
using System.Web.Security;
using WebMatrix.WebData;

namespace SePantry_1.Controllers
{
    public class UserProfilesController : Controller
    {
        private UsersContext db = new UsersContext();

        [Authorize(Roles = "admin")]
        // GET: UserProfiles
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            {
                //paging
                ViewBag.CurrentSort = sortOrder;
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;
                var customer = from s in db.UserProfiles
                               select s;
                //sorting data
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "UserName" : "";
                ViewBag.NameSortParm1 = String.IsNullOrEmpty(sortOrder) ? "FirstName" : "";
                ViewBag.NameSortParm2 = String.IsNullOrEmpty(sortOrder) ? "LastName" : "";
                ViewBag.NameSortParm3 = String.IsNullOrEmpty(sortOrder) ? "Email" : "";
                ViewBag.NameSortParm4 = String.IsNullOrEmpty(sortOrder) ? "WNumber" : "";
                // ViewBag.NameSortParm4 = String.IsNullOrEmpty(sortOrder) ? "passwrord" : "";
                switch (sortOrder)
                {
                    case "firstName":
                        customer = customer.OrderBy(s => s.UserName);
                        break;
                    case "lastName":
                        customer = customer.OrderBy(s => s.FirstName);
                        break;
                    case "emailAddress":
                        customer = customer.OrderBy(s => s.LastName);
                        break;
                    case "wNumber":
                        customer = customer.OrderBy(s => s.Email);
                        break;
                    case "WNumber":
                        customer = customer.OrderBy(s => s.WNumber);
                        break;
                    default:
                        customer = customer.OrderBy(s => s.FirstName);
                        break;
                }
                //end of sorting
                //for searching data

                if (!String.IsNullOrEmpty(searchString))
                {
                    searchString = searchString.Trim();//ignore white space
                    customer = customer.Where(s => s.UserName.Contains(searchString)
                            || s.FirstName.Contains(searchString)
                             || s.LastName.Contains(searchString)
                               || s.Email.Contains(searchString)
                               || s.WNumber.Contains(searchString)); ;
                }


                int pageSize = 10;
                int pageNumber = (page ?? 1);
                return View(customer.ToPagedList(pageNumber, pageSize));
                //return View(db.UserProfiles.ToList());
            }
        }
        [Authorize(Roles = "admin")]
        // GET: UserProfiles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }
        [Authorize(Roles = "admin")]
        // GET: UserProfiles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,UserName,FirstName,LastName,Email,WNumber")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                db.UserProfiles.Add(userProfile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userProfile);
        }

        // GET: UserProfiles/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // POST: UserProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "UserId,UserName,FirstName,LastName,Email,WNumber")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userProfile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userProfile);
        }

        // GET: UserProfiles/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // POST: UserProfiles/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var tmpuser = "";
            var ctx = new UsersContext();
            using (ctx)
            {
                var firstOrDefault = ctx.UserProfiles.FirstOrDefault(us => us.UserId == id);
                if (firstOrDefault != null)
                    tmpuser = firstOrDefault.UserName;
            }

            string[] allRoles = Roles.GetRolesForUser(tmpuser);
            Roles.RemoveUserFromRoles(tmpuser, allRoles);

            //Roles.RemoveUserFromRole(tmpuser, "RoleName");

            ((SimpleMembershipProvider)Membership.Provider).DeleteAccount(tmpuser);
            Membership.Provider.DeleteUser(tmpuser, true);
            Membership.DeleteUser(tmpuser, true);
            //UserProfile userProfile = db.UserProfiles.Find(id);
            
            ////webpages_UsersInRoles webpages_UsersInRoles = db.webpages_UsersInRoles.Find(id);
            //db.UserProfiles.Remove(userProfile);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult autocomplete_users(string keyword)
        {
            return Json(getUsers(keyword), JsonRequestBehavior.AllowGet);
        }

        public List<UserProfile> getUsers(string keyword)
        {
            return (
               from u in db.UserProfiles
               select u
               ).ToList();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SePantry-1/Views/AdminDashboard/index.cshtml
@if (Roles.GetRolesForUser().Contains("Admin"))
{
    ViewBag.Title = "Admin Dashboard";

    <h2>Admin Dashboard</h2>

    <br />
    <!--<ul class="nav nav-pills">
        <li class="active"><a>Admin Home</a></li>
        <li>@Html.ActionLink("Customers", "Index", "UserProfiles")</li>
        <li>@Html.ActionLink("Checkout", "Index", "Admin")</li>

        <li>@Html.ActionLink("EditRoles", "RoleAddToUser", "RoleManager")</li>
        <li>@Html.ActionLink("MakeUserAccount", "Index", "Admin")</li>
        <li>@Html.ActionLink("Email", "MassEmail", "Email")</li>
    </ul>-->

    <div class="row" style="min-height:550px;">
        <div class="col-md-12 dashboard-container">
            <div class="col-md-2">
                <!-- required for floating -->
                <!-- Nav tabs -->
                <ul class="nav nav-tabs tabs-left">
                    <li class="active text-center">
                        <a href="#searchinventory" data-toggle="tab">
                            <h4 class="glyphicon glyphicon-search"></h4><br />Search Inventory
                        </a>
                    </li>
                    <li class="text-center">
                        <a href="/Active_Products/Create"><h4 class="glyphicon glyphicon-plus"></h4><br />Add Products</a>
                    </li>
                    <li class="text-center">
                        <a href="#startcheckout" data-toggle="tab">
                            <h4 class="glyphicon glyphicon-shopping-cart"></h4><br />Start Product Checkout
                        </a>
                    </li>
                    <li class="text-center">
                        <a href="/Email/MassEmail/"><h4 class="glyphicon glyphicon-envelope"></h4><br />Email Communication</a>
                    </li>
                    <li class="text-center">
                        <a href="#manageusers" data-toggle="tab"><h4 class="glyphicon glyphicon-user"></h4><br />Manage Users</a>
                    </li>
                </ul>
            </div>
            
            <div class="col-md-10">
                <!-- Tab panes -->
                <div class="tab-content">
                    @*<div class="tab-pane active" id="addproducts">
                        @model SePantry_1.Models.Active_Product

                        <h3>Product Inventory - Scan a product to start adding</h3>
                        <hr />
                        <div id="productidcheck">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true)

                                <div class="form-horizontal">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-5">
                                            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>
                            }
                        </div>

                    </div>*@
                    <div class="tab-pane active" id="searchinventory">
                        <h3>Search Inventory</h3>
                        <p>Scan barcode number or enter anything about the product to search the inventory.</p>
                        <br />
                        @using (Html.BeginForm("Index","Active_Products"))
                        {
                            <input type="text" name="SearchString" class="form-control col-md-6" placeholder="Search Inventory.." />
                            <br /><br /><br />
                        <input class="registerButton" type="submit" value="Search" style="margin-left:0;"/><br />
                        }
                    </div>

                    <div class="tab-pane" id="startcheckout">
                        <div id="checkout1">
                            <h3>Enter a user for whom you would like to check out : </h3>
                            <input type="text" id="prod_user" class="form-control col-md-7" />
                        </div>

                        <div id="checkout2">
                            <h3>Enter product description or scan to begin checking out</h3>
                            <input type="text" id="checkout-scanner" class="form-control col-md-7" />
                        </div>
                    </div>

                    <div class="tab-pane" id="emailcommunication">Messages Tab.</div>
                    <div class="tab-pane" id="manageusers">
                        @if (Roles.GetRolesForUser().Contains("Admin"))
                        {
                            <h3>User and Role Management</h3>                        
                            <br /><h4>Manage User Roles</h4>
                            <br />
                            <ul class="nav nav-pills">
                                <li>@Html.ActionLink("Create User Roles", "RoleCreate", "RoleManager")</li>
                                <li>@Html.ActionLink("View Role Index", "RoleIndex", "RoleManager")</li>
                                <li>@Html.ActionLink("Assign Roles to a User", "RoleAddToUser", "RoleManager")</li>
                            </ul>

                            <br />
                            
                            <h4>Manage Customers</h4>
                            <br />
                            <ul class="nav nav-pills">
                                <li>@Html.ActionLink("View Customers", "Index", "UserProfiles")</li>
                                <li>@Html.ActionLink("Edit Roles", "RoleAddToUser", "RoleManager")</li>
                            </ul>
                            
                            <br />
                            
                            <h4>Manage Donors</h4>
                            <ul class="nav nav-pills">
                                <li>@Html.ActionLink("View Donors List", "Index", "PDonors")</li>
                                <li>@Html.ActionLink("Add Donors", "Create", "PDonors")</li>
                            </ul>
                        }
                    </div>
                    <!--<div class="tab-pane" id="manageusers">Manage Users Tab.</div>-->
                </div>
            </div>

        </div>
    </div>
    <script>
    $("#Id").submit(function (e) {
        //alert("Handler for .submit() called.");
        e.preventDefault();
        var url = '@Url.Action("checkProductID", "Active_Products")';
        var postdata = $('#Id').val();
        alert($('#Id').val());
        $.ajax({
            type: "POST",
            url: url,
            data: postdata.serialize(),
            success: function (data) {

            }
        });
        return false;
    });

    $('#prod_user').on("click", user_id_autocomplete());

    function user_id_autocomplete() {
        $("#prod_user").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '@Url.Action("autocomplete_users", "UserProfiles")',
                        dataType: "json",
                        data: { term: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return {
                                    label: item.FirstName + " " + item.LastName,
                                    id: item.Id
                                };
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function (event, ui) {
                    $('#prod_user').val(ui.item.id);
                    $('#checkout1').hide();
                    $('#checkout2').show();
                    // alert($('.id-autocom').val());
                }
            });
        }
        //Fixing the autocomplete bug
        jQuery.ui.autocomplete.prototype._resizeMenu = function () {
            var ul = this.menu.element;
            ul.outerWidth(this.element.outerWidth());
        }

        //On Change Scanner
        $('#checkout-scanner').on("click", product_autocomplete());

        function product_autocomplete() {
            $("#checkout-scanner").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '@Url.Action("product_list", "Active_Products")',
                        dataType: "json",
                        data: { term: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return {
                                    label: "Item ID : " + item.Id + " - " + item.title + " - " + item.manufacturer,
                                    id: item.Id
                                };
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function (event, ui) {
                    $('#prod_user').val(ui.item.id);
//                    $('#checkout2').show();
                    // alert($('.id-autocom').val());
                }
            });
        }
    </script>
}