SePantry-1/Controllers/Active_ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SePantry_1.Models;
using PagedList;
using PagedList.Mvc;


namespace SePantry_1.Controllers
{
    public class Active_ProductsController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Active_Products/

        public ActionResult Index(string sortOrder,string searchString,string currentFilter,int? page)
        {
            //paging
            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var product = from s in db.Active_Products
                          select s;
            //sorting data
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "category" : "";
            ViewBag.NameSortParm1 = String.IsNullOrEmpty(sortOrder) ? "title": "";
            ViewBag.NameSortParm2 = String.IsNullOrEmpty(sortOrder) ? "manufacturer" : "";
            ViewBag.NameSortParm3 = String.IsNullOrEmpty(sortOrder) ? "isCanned" : "";
            ViewBag.NameSortParm4 = String.IsNullOrEmpty(sortOrder) ? "product_code" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            switch (sortOrder)
            {
                case "category":
                    product = product.OrderBy(s => s.category);
                    break;
                case "title":
                    product = product.OrderBy(s => s.title);
                    break;
                case "manufacturer":
                    product = product.OrderBy(s => s.manufacturer);
                    break;
                case "isCanned":
                    product = product.OrderBy(s => s.isCanned);
                    break;
                case "product_code":
                    product = product.OrderBy(s => s.product_code);
                    break;
                default:
                    product = product.OrderBy(s => s.category);
                    break;
            }
            //end of sorting
           
            //for searching data
            
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.Trim();//ignore white space
                product = product.Where(s => s.category.Contains(searchString)
                        || s.title.Contains(searchString)
                         || s.manufacturer.Contains(searchString));
            }


            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(product.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Active_Products/Details/5

        public ActionResult Details(int id = 0)
        {
            Active_Product active_product = db.Active_Products.Find(id);
            if (active_product == null)
            {
                return HttpNotFound();
            }
            return View(active_product);
        }

        //
        // GET: /Active_Products/Create
        [Authorize(Roles="admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Active_Products/Create

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Active_Product active_product)
        {
            if (ModelState.IsValid)
            {
                db.Active_Products.Add(active_product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(active_product);
        }

        //
        // GET: /Active_Products/Edit/5

         [Authorize(Roles = "admin")]
        public ActionResult Edit(int id = 0)
        {
            Active_Product active_product = db.Active_Products.Find(id);
            if (active_product == null)
            {
                return HttpNotFound();
            }
            return View(active_product);
        }

        //
        // POST: /Active_Products/Edit/5

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Active_Product active_product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(active_product).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(active_product);
        }

        //
        // GET: /Active_Products/Delete/5
         [Authorize(Roles = "admin")]
        public ActionResult Delete(int id = 0)
        {
            Active_Product active_product = db.Active_Products.Find(id);
            if (active_product == null)
            {
                return HttpNotFound();
            }
            return View(active_product);
        }

        //
        // POST: /Active_Products/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Active_Product active_product = db.Active_Products.Find(id);
            db.Active_Products.Remove(active_product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult autocomplete_donor(string keyword)
        {
            return Json(getDonors(keyword), JsonRequestBehavior.AllowGet);
        }

        public List<Donor> getDonors(string keyword)
        {
            return (
                from Donors in db.Donors
               // where (Donors.FirstName.Contains(keyword))
                //where (item => Donors.FirstName.Any(keyword => Donors.LastName.Contains(keyword)))
                select Donors
                ).ToList();
        }

        //List of products
        [HttpGet]
        public ActionResult product_list(string keyword)
        {
            return Json(product_list_gen(keyword), JsonRequestBehavior.AllowGet);
        }

        public List<Active_Product> product_list_gen(string keyword)
        {
            
            return (
                from Active_Products in db.Active_Products
                // where (Donors.FirstName.Contains(keyword))
                //where (item => Donors.FirstName.Any(keyword => Donors.LastName.Contains(keyword)))
              select Active_Products
                ).ToList();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SePantry-1/Controllers/AdminDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SePantry_1.Models;
using System.Data;
using System.Data.Entity;

namespace SePantry_1.Controllers
{
    public class AdminDashboardController : Controller
    {

        private UsersContext db = new UsersContext();

        // GET: AdminDashboard
        public ActionResult Index()
        {
            //Let the authorized admin view the Dashboard
            if (Roles.GetRolesForUser().Contains("Admin"))
            {
                return View();
            }
            else
            {
                //Redirect the non-authorized users to homepage
                return RedirectToAction("Login", "Account");
            }
        }

        // GET: /Active_Products/Create
        [Authorize(Roles = "admin")]
        public ActionResult CreateProducts()
        {
            return View();
        }

        //
        // POST: /Active_Products/Create

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProducts(Active_Product active_product)
        {
            if (ModelState.IsValid)
            {
                db.Active_Products.Add(active_product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(active_product);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Search_Inventory()
        {
            if (!string.IsNullOrEmpty(Request.Form["search-inventory"]))
            {
                
            }
            return View();
        }
    }
}

SePantry-1/Controllers/Product_DetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SePantry_1.Models;

namespace SePantry_1.Controllers
{
    public class Product_DetailController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Product_Detail/

        public ActionResult Index()
        {
            
            return View(db.Product_Details.ToList());
        }

        //
        // GET: /Product_Detail/Details/5

        public ActionResult Details(int id = 0)
        {
            Product_Detail product_detail = db.Product_Details.Find(id);
            if (product_detail == null)
            {
                return HttpNotFound();
            }
            return View(product_detail);
        }

        //
        // GET: /Product_Detail/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Product_Detail/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product_Detail product_detail)
        {
            if (ModelState.IsValid)
            {
                db.Product_Details.Add(product_detail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product_detail);
        }

        //
        // GET: /Product_Detail/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Product_Detail product_detail = db.Product_Details.Find(id);
            if (product_detail == null)
            {
                return HttpNotFound();
            }
            return View(product_detail);
        }

        //
        // POST: /Product_Detail/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product_Detail product_detail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product_detail).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product_detail);
        }

        //
        // GET: /Product_Detail/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Product_Detail product_detail = db.Product_Details.Find(id);
            if (product_detail == null)
            {
                return HttpNotFound();
            }
            return View(product_detail);
        }

        //
        // POST: /Product_Detail/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product_Detail product_detail = db.Product_Details.Find(id);
            db.Product_Details.Remove(product_detail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SePantry-1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - SEPantry</title>
    
    <meta name="viewport" content="width=device-width" />
    
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/themes/ui-lightness/jquery-ui.ui-lightness.css")
    @Styles.Render("~/Content/custom_style.css")
    @Styles.Render("~/Content/for_login.css")
    @Styles.Render("~/Content/animate-custom.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
 
    <script src="~/Scripts/for_popup_login.js"></script>
  
    <style>
        /*header *{
            background-color:#048545;
        }*/
        /*float-right{
            background-color:#048545;
        }
        float-left{
            background-color:#048545;
        }*/
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    
                </button>
                <a class="navbar-brand" href="~/"><img src="~/Content/images/sepantry-l.png" width="350" height="49" /></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    @if (!Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    }
                    
                    <li>@Html.ActionLink("Inventory", "Index", "Active_Products")</li>
                     
                    @if (Roles.GetRolesForUser().Contains("Admin")) {

                     <li>@Html.ActionLink("Admin Dashboard", "Index", "AdminDashboard")</li>
                       
                    }
                    @if (Roles.GetRolesForUser().Contains("User"))
                    {
                        <li>@Html.ActionLink("My History", "Index", "Product_Detail")</li>
                    }

                    <li>@Html.Partial("_LoginPartial")</li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    
    <!-- BODY -->
    <div id="body">
        <div class="container">
            <div class="content-start">
             
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
        </div>
            </div>
    </div>
    
    <!-- FOOTER-->
    <footer>
        <div class="container">
        <div class="content-wrapper">
            <div class="footer-center">
                <p style="text-align:left; font-weight:bold;" class="col-md-5">&copy;Southeastern Food Pantry - @DateTime.Now.Year</p>
                <p style="text-align:right; font-weight:bold;" class="footer-links">@Html.ActionLink("Home", "Index", "Home") | @Html.ActionLink("Contact", "Contact", "Home")</p>
            </div>
            
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>